/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 *
 * NOTE: Paths have been updated to match the current backend routes.
 * Canvas creation/retrieval now goes through /document endpoints.
 * Regenerate from backend OpenAPI spec with `pnpm codegen:all` in the monorepo.
 */

export interface paths {
	/**
	 * File upload presigned URL endpoint.
	 * NOTE: Manually added — regenerate from backend OpenAPI spec once API key auth is enabled on this route.
	 */
	"/files": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["get_upload_url"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/document": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["get_all_documents"];
		put?: never;
		post: operations["create_documents"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/document/{document_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["get_document"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch: operations["patch_document"];
		trace?: never;
	};
	"/document/{document_id}/metadata": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put: operations["update_document_metadata"];
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/canvas/{canvas_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["get_canvas"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch: operations["patch_canvas"];
		trace?: never;
	};
	"/canvas/{canvas_id}/metadata": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["get_canvas_metadata"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		/** @description Represents the configuration for an agent that can interact with the canvas. */
		AgentConfig: {
			apiKeyId?: string | null;
			prompt: string;
		};
		AppendDocumentContentParams: {
			content: string;
		};
		AppendNodeContentParams: {
			content: string;
			id: string;
		};
		CanvasView: {
			edges: components["schemas"]["Edge"][];
			nodes: components["schemas"]["NodeEditorView"][];
		};
		/**
		 * @description This view contains all the necessary fields to display a canvas in the react flow editor.
		 *     INCLUDING the S3 download URL for all file nodes.
		 */
		CanvasEditorView: {
			_id: components["schemas"]["ObjectId"];
			description?: string | null;
			edges: components["schemas"]["Edge"][];
			isTemplate: boolean;
			name: string;
			nodes: components["schemas"]["NodeEditorView"][];
			ownerId: string;
		};
		/** @description This view contains all the necessary fields to display a canvas in the dashboard. */
		CanvasSummaryView: {
			_id: components["schemas"]["ObjectId"];
			description?: string | null;
			isTemplate: boolean;
			name: string;
			pinned?: boolean;
			updatedAt: string;
		};
		/** @enum {string} */
		ConnectionSide: "left" | "right" | "top" | "bottom";
		CreateEdgeParams: {
			fromNodeId: string;
			fromSide: components["schemas"]["ConnectionSide"];
			id?: string | null;
			label?: string | null;
			toNodeId: string;
			toSide: components["schemas"]["ConnectionSide"];
		};
		CreateNodeData:
			| {
					_content: {
						title?: string | null;
					};
					/** @enum {string} */
					_type: "Group";
			  }
			| {
					_content: {
						document_id: string;
					};
					/** @enum {string} */
					_type: "ExistingDocument";
			  }
			| {
					_content: components["schemas"]["NewDocumentParams"];
					/** @enum {string} */
					_type: "NewDocument";
			  };
		CreateNodeParams: {
			data?: null | components["schemas"]["CreateNodeData"];
			/** Format: double */
			height: number;
			id?: string | null;
			/** Format: double */
			width: number;
			/** Format: double */
			x: number;
			/** Format: double */
			y: number;
		};
		DeleteEdgeParams: {
			id: string;
		};
		DeleteNodeParams: {
			id: string;
		};
		DocumentContentView:
			| {
					_content: components["schemas"]["api.create_nodes.TextView"];
					/** @enum {string} */
					_type: "Text";
			  }
			| {
					_content: components["schemas"]["FileStoreView"];
					/** @enum {string} */
					_type: "File";
			  }
			| {
					_content: components["schemas"]["Youtube"];
					/** @enum {string} */
					_type: "Youtube";
			  }
			| {
					_content: components["schemas"]["Website"];
					/** @enum {string} */
					_type: "Website";
			  }
			| {
					_content: components["schemas"]["CanvasView"];
					/** @enum {string} */
					_type: "Canvas";
			  };
		ContentMetadata:
			| {
					/** @enum {string} */
					_type: "Canvas";
			  }
			| {
					/** @enum {string} */
					_type: "Text";
			  }
			| (components["schemas"]["FileStoreMetadata"] & {
					/** @enum {string} */
					_type: "File";
			  })
			| {
					/** @enum {string} */
					_type: "Youtube";
			  }
			| {
					/** @enum {string} */
					_type: "Website";
			  }
			| {
					/** @enum {string} */
					_type: "Bundle";
			  };
		DocumentView: {
			_id: components["schemas"]["ObjectId"];
			archived?: boolean;
			content: components["schemas"]["DocumentContentView"];
			createdAt: string;
			description?: string | null;
			/** @description Flag indicating whether the document was generated by an agent. */
			generated: boolean;
			inLibrary?: boolean;
			isFavorite?: boolean;
			ownerId: string;
			tags?: string[];
			thumbnail?: null | components["schemas"]["S3ObjectView"];
			title?: string | null;
			updatedAt: string;
		};
		/** @description This view contains the non-content metadata needed to display a document in the library. */
		DocumentMetadataView: {
			_id: components["schemas"]["ObjectId"];
			archived?: boolean;
			content: components["schemas"]["ContentMetadata"];
			createdAt: string;
			description?: string | null;
			deletedAt?: string | null;
			inLibrary?: boolean;
			isFavorite?: boolean;
			permissions?: components["schemas"]["PermissionView"] | null;
			sharingConfig?: components["schemas"]["SharingConfig"] | null;
			tags?: string[];
			thumbnail?: null | components["schemas"]["S3ObjectView"];
			title?: string | null;
			updatedAt: string;
		};
		DocumentOperation:
			| (components["schemas"]["SetTitleParams"] & {
					/** @enum {string} */
					_type: "setTitle";
			  })
			| (components["schemas"]["SetFavoriteStateParams"] & {
					/** @enum {string} */
					_type: "setFavoriteState";
			  })
			| (components["schemas"]["SetContentParams"] & {
					/** @enum {string} */
					_type: "setContent";
			  })
			| (components["schemas"]["AppendDocumentContentParams"] & {
					/** @enum {string} */
					_type: "appendDocumentContent";
			  });
		Edge: {
			_id: components["schemas"]["ObjectId"];
			color: string;
			createdAt: string;
			fromNode: components["schemas"]["ObjectId"];
			fromSide: components["schemas"]["ConnectionSide"];
			label: string;
			toNode: components["schemas"]["ObjectId"];
			toSide: components["schemas"]["ConnectionSide"];
			updatedAt: string;
		};
		FileStoreView:
			| (components["schemas"]["S3ObjectView"] & {
					/** @enum {string} */
					_type: "s3Object";
			  })
			| (components["schemas"]["GoogleDriveObject"] & {
					/** @enum {string} */
					_type: "googleDriveObject";
			  });
		FileMetadata: {
			file_type: string;
		};
		FileStoreMetadata:
			| {
					s3Object: components["schemas"]["FileMetadata"];
			  }
			| {
					googleDrive: components["schemas"]["FileMetadata"];
			  };
		GoogleDriveObject: {
			file_type: string;
			id: string;
		};
		Group: {
			title?: string | null;
		};
		Invite: {
			email: string;
			permission: components["schemas"]["Permission"];
		};
		MessageRef: {
			conversationId: components["schemas"]["ObjectId"];
			messageId: components["schemas"]["ObjectId"];
		};
		NewDocumentParams: {
			content?: null | components["schemas"]["DocumentContentView"];
			description?: string | null;
			generated?: boolean | null;
			id?: string | null;
			tags?: string[] | null;
			title?: string | null;
		};
		Node: {
			_id: components["schemas"]["ObjectId"];
			color: string;
			createdAt: string;
			data: components["schemas"]["NodeData"];
			/** Format: double */
			height: number;
			updatedAt: string;
			/** Format: double */
			width: number;
			/** Format: double */
			x: number;
			/** Format: double */
			y: number;
		};
		/**
		 * @description A node's data can either be a reference to a document or be a group container.
		 *     Note: We need to add content to serde tag because serializing the struct as
		 *     {"_type": "DocumentId", ...somehow inline ObjectId...} doesn't work with BSON
		 */
		NodeData:
			| {
					_content: components["schemas"]["ObjectId"];
					/** @enum {string} */
					_type: "DocumentId";
			  }
			| {
					_content: components["schemas"]["Group"];
					/** @enum {string} */
					_type: "Group";
			  };
		NodeDataView:
			| (components["schemas"]["DocumentView"] & {
					/** @enum {string} */
					_type: "Document";
			  })
			| (components["schemas"]["Group"] & {
					/** @enum {string} */
					_type: "Group";
			  });
		/** @description This view modifies the node content to contain the S3 download URL if the content is of type File. */
		NodeEditorView: {
			_id: components["schemas"]["ObjectId"];
			color: string;
			createdAt: string;
			data: components["schemas"]["NodeDataView"];
			/** Format: double */
			height: number;
			updatedAt: string;
			/** Format: double */
			width: number;
			/** Format: double */
			x: number;
			/** Format: double */
			y: number;
		};
		/** @description Represents a MongoDB ObjectId in a format compatible with JSON Schema. */
		ObjectId: {
			$oid: string;
		};
		Permission: "Read" | "Comment" | "Edit";
		PermissionView: "owner" | "read" | "comment" | "edit";
		Operation:
			| (components["schemas"]["SetNameParams"] & {
					/** @enum {string} */
					_type: "setName";
			  })
			| (components["schemas"]["CreateNodeParams"] & {
					/** @enum {string} */
					_type: "createNode";
			  })
			| (components["schemas"]["SetNodePositionParams"] & {
					/** @enum {string} */
					_type: "setNodePosition";
			  })
			| (components["schemas"]["SetNodeSizeParams"] & {
					/** @enum {string} */
					_type: "setNodeSize";
			  })
			| (components["schemas"]["SetNodeTitleParams"] & {
					/** @enum {string} */
					_type: "setNodeTitle";
			  })
			| (components["schemas"]["SetNodeFavoriteStateParams"] & {
					/** @enum {string} */
					_type: "setNodeFavoriteState";
			  })
			| (components["schemas"]["SetNodeColorParams"] & {
					/** @enum {string} */
					_type: "setNodeColor";
			  })
			| (components["schemas"]["SetNodeContentParams"] & {
					/** @enum {string} */
					_type: "setNodeContent";
			  })
			| (components["schemas"]["AppendNodeContentParams"] & {
					/** @enum {string} */
					_type: "appendNodeContent";
			  })
			| (components["schemas"]["DeleteNodeParams"] & {
					/** @enum {string} */
					_type: "deleteNode";
			  })
			| (components["schemas"]["CreateEdgeParams"] & {
					/** @enum {string} */
					_type: "createEdge";
			  })
			| (components["schemas"]["SetEdgeLabelParams"] & {
					/** @enum {string} */
					_type: "setEdgeLabel";
			  })
			| (components["schemas"]["DeleteEdgeParams"] & {
					/** @enum {string} */
					_type: "deleteEdge";
			  })
			| (components["schemas"]["SetEdgePositionParams"] & {
					/** @enum {string} */
					_type: "setEdgePosition";
			  });
		S3Object: {
			bucket: string;
			file_type: string;
			key: string;
		};
		S3ObjectView: {
			download_url: string;
			file_type: string;
			key: string;
		};
		SetContentParams: {
			content: components["schemas"]["DocumentContentView"];
		};
		SetEdgeLabelParams: {
			id: string;
			label: string;
		};
		SetEdgePositionParams: {
			fromNodeId: string;
			fromSide: components["schemas"]["ConnectionSide"];
			id: string;
			toNodeId: string;
			toSide: components["schemas"]["ConnectionSide"];
		};
		SetFavoriteStateParams: {
			isFavorite: boolean;
		};
		SetNameParams: {
			name: string;
		};
		SetNodeColorParams: {
			color?: string | null;
			id: string;
		};
		SetNodeContentParams: {
			content: components["schemas"]["DocumentContentView"];
			id: string;
		};
		SetNodeFavoriteStateParams: {
			id: string;
			isFavorite: boolean;
		};
		SetNodePositionParams: {
			id: string;
			/** Format: double */
			x: number;
			/** Format: double */
			y: number;
		};
		SetNodeSizeParams: {
			/** Format: double */
			height: number;
			id: string;
			/** Format: double */
			width: number;
		};
		SetNodeTitleParams: {
			id: string;
			title?: string | null;
		};
		SetTitleParams: {
			title: string;
		};
		SharingConfig: {
			invites: components["schemas"]["Invite"][];
			urlPermission?: components["schemas"]["Permission"] | null;
		};
		Website: {
			url: string;
		};
		Youtube: {
			videoId: string;
		};
		/** @description Client-facing type for canvas creation. The client transforms this to a document creation request. */
		"api.create_canvas.Request": {
			description?: string | null;
			name?: string | null;
		};
		/** @description Client-facing type for canvas creation response. Extracted from the document creation response. */
		"api.create_canvas.Response": {
			canvas_id: components["schemas"]["ObjectId"];
		};
		/** @description Client-facing type for canvas list response. Built from document list response filtered to canvas type. */
		"api.get_canvases.Response": {
			data: components["schemas"]["CanvasSummaryView"][];
		};
		"api.get_all_documents.Response": {
			documents: components["schemas"]["DocumentMetadataView"][];
		};
		"api.patch_document.Request": {
			operations: components["schemas"]["DocumentOperation"][];
		};
		"api.patch_canvas.Request": {
			operations: components["schemas"]["Operation"][];
		};
		"api.create_documents.Request": {
			documents: components["schemas"]["api.create_documents.RequestDocument"][];
		};
		"api.create_documents.RequestDocument": {
			_id?: string | null;
			content?: null | components["schemas"]["DocumentContentView"];
			description?: string | null;
			tags?: string[] | null;
			title?: string | null;
		};
		"api.create_documents.Response": {
			documents: components["schemas"]["DocumentView"][];
		};
		"api.create_nodes.TextView": {
			agentConfig?: null | components["schemas"]["AgentConfig"];
			origin?: null | components["schemas"]["MessageRef"];
			text?: string | null;
		};
		/** NOTE: Manually added — regenerate from backend OpenAPI spec once API key auth is enabled. */
		"api.get_upload_url.Request": {
			s3_key: string;
		};
		/** NOTE: Manually added — regenerate from backend OpenAPI spec once API key auth is enabled. */
		"api.get_upload_url.Response": {
			url: string;
			fields: Record<string, string>;
		};
		"api.update_document_metadata.Request": {
			archived?: boolean | null;
			description?: string | null;
			inLibrary?: boolean | null;
			isFavorite?: boolean | null;
			thumbnailS3Key?: string | null;
			title?: string | null;
		};
		"api.update_document_metadata.Response": {
			updated: boolean;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	get_canvas: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description The ID of the canvas to retrieve */
				canvas_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Canvas retrieved successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CanvasEditorView"];
				};
			};
			/** @description Canvas not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_canvas_metadata: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description The ID of the canvas to retrieve */
				canvas_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Canvas retrieved successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["DocumentMetadataView"];
				};
			};
			/** @description Canvas not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_all_documents: {
		parameters: {
			query?: {
				/** @description Filter documents by tag */
				tag?: string;
				/** @description Filter documents by favorite status */
				isFavorite?: boolean;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Documents retrieved successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["api.get_all_documents.Response"];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	create_documents: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["api.create_documents.Request"];
			};
		};
		responses: {
			/** @description Document created successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["api.create_documents.Response"];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_document: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description The ID of the document to retrieve */
				document_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Document retrieved successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["DocumentView"];
				};
			};
			/** @description Document not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	patch_document: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description The ID of the document to update */
				document_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["api.patch_document.Request"];
			};
		};
		responses: {
			/** @description Document updated successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Document not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	update_document_metadata: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description The ID of the document to retrieve */
				document_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["api.update_document_metadata.Request"];
			};
		};
		responses: {
			/** @description Document retrieved successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["api.update_document_metadata.Response"];
				};
			};
			/** @description Document not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	patch_canvas: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description The ID of the canvas to update */
				canvas_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["api.patch_canvas.Request"];
			};
		};
		responses: {
			/** @description Canvas updated successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	/** NOTE: Manually added — regenerate from backend OpenAPI spec once API key auth is enabled. */
	get_upload_url: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["api.get_upload_url.Request"];
			};
		};
		responses: {
			/** @description Presigned upload URL generated successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["api.get_upload_url.Response"];
				};
			};
			/** @description Unauthorized — API key auth not yet available for this route */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
}
