/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  /**
   * File upload presigned URL endpoint.
   * NOTE: Manually added — regenerate from backend OpenAPI spec once API key auth is enabled on this route.
   */
  "/files": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["get_upload_url"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/canvas": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_canvases"];
    put?: never;
    post: operations["create_canvas"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/canvas/{canvas_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_canvas_by_id"];
    put: operations["update_canvas"];
    post?: never;
    delete: operations["delete_canvas"];
    options?: never;
    head?: never;
    patch: operations["patch_canvas"];
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @description Represents the configuration for an agent that can interact with the canvas. */
    AgentConfig: {
      apiKeyId?: string | null;
      prompt: string;
    };
    AppendNodeContentParams: {
      content: string;
      id: string;
    };
    Canvas: {
      _id: components["schemas"]["ObjectId"];
      copiedFrom?: null | components["schemas"]["CanvasRef"];
      createdAt: string;
      deletedAt?: string;
      description?: string | null;
      edges: components["schemas"]["Edge"][];
      isTemplate: boolean;
      name: string;
      nodes: components["schemas"]["Node"][];
      ownerId: string;
      pinned?: boolean;
      sharingConfig?: null | components["schemas"]["SharingConfig"];
      thumbnail?: null | components["schemas"]["S3Object"];
      updatedAt: string;
      version: components["schemas"]["ObjectId"];
    };
    /**
     * @description This view contains all the necessary fields to display a canvas in the react flow editor.
     *     INCLUDING the S3 download URL for all file nodes.
     */
    CanvasEditorView: {
      _id: components["schemas"]["ObjectId"];
      description?: string | null;
      edges: components["schemas"]["Edge"][];
      isTemplate: boolean;
      name: string;
      nodes: components["schemas"]["NodeEditorView"][];
      ownerId: string;
    };
    CanvasRef:
      | {
          /** @enum {string} */
          _type: "publicCanvas";
          id: components["schemas"]["ObjectId"];
        }
      | {
          /** @enum {string} */
          _type: "canvas";
          id: components["schemas"]["ObjectId"];
        };
    /** @description This view contains all the necessary fields to display a canvas in the dashboard. */
    CanvasSummaryView: {
      _id: components["schemas"]["ObjectId"];
      description?: string | null;
      isTemplate: boolean;
      name: string;
      pinned?: boolean;
      sharingConfig?: null | components["schemas"]["SharingConfig"];
      thumbnail?: null | components["schemas"]["S3ObjectView"];
      updatedAt: string;
    };
    /** @enum {string} */
    ConnectionSide: "left" | "right" | "top" | "bottom";
    CreateEdgeParams: {
      fromNodeId: string;
      fromSide: components["schemas"]["ConnectionSide"];
      id?: string | null;
      label?: string | null;
      toNodeId: string;
      toSide: components["schemas"]["ConnectionSide"];
    };
    CreateNodeData:
      | {
          _content: {
            title?: string | null;
          };
          /** @enum {string} */
          _type: "Group";
        }
      | {
          _content: {
            document_id: string;
          };
          /** @enum {string} */
          _type: "ExistingDocument";
        }
      | {
          _content: components["schemas"]["NewDocumentParams"];
          /** @enum {string} */
          _type: "NewDocument";
        };
    CreateNodeParams: {
      data?: null | components["schemas"]["CreateNodeData"];
      /** Format: double */
      height: number;
      id?: string | null;
      /** Format: double */
      width: number;
      /** Format: double */
      x: number;
      /** Format: double */
      y: number;
    };
    DeleteEdgeParams: {
      id: string;
    };
    DeleteNodeParams: {
      id: string;
    };
    DocumentContentView:
      | {
          _content: components["schemas"]["api.create_nodes.TextView"];
          /** @enum {string} */
          _type: "Text";
        }
      | {
          _content: components["schemas"]["FileStoreView"];
          /** @enum {string} */
          _type: "File";
        }
      | {
          _content: components["schemas"]["Youtube"];
          /** @enum {string} */
          _type: "Youtube";
        }
      | {
          _content: components["schemas"]["Website"];
          /** @enum {string} */
          _type: "Website";
        };
    DocumentView: {
      _id: components["schemas"]["ObjectId"];
      archived?: boolean;
      content: components["schemas"]["DocumentContentView"];
      createdAt: string;
      /** @description Flag indicating whether the document was generated by an agent. */
      generated: boolean;
      isFavorite?: boolean;
      ownerId: string;
      tags?: string[];
      title?: string | null;
      updatedAt: string;
    };
    Edge: {
      _id: components["schemas"]["ObjectId"];
      color: string;
      createdAt: string;
      fromNode: components["schemas"]["ObjectId"];
      fromSide: components["schemas"]["ConnectionSide"];
      label: string;
      toNode: components["schemas"]["ObjectId"];
      toSide: components["schemas"]["ConnectionSide"];
      updatedAt: string;
    };
    FileStoreView:
      | (components["schemas"]["S3ObjectView"] & {
          /** @enum {string} */
          _type: "s3Object";
        })
      | (components["schemas"]["GoogleDriveObject"] & {
          /** @enum {string} */
          _type: "googleDriveObject";
        });
    GoogleDriveObject: {
      file_type: string;
      id: string;
    };
    Group: {
      title?: string | null;
    };
    MessageRef: {
      conversationId: components["schemas"]["ObjectId"];
      messageId: components["schemas"]["ObjectId"];
    };
    NewDocumentParams: {
      content?: null | components["schemas"]["DocumentContentView"];
      description?: string | null;
      generated?: boolean | null;
      id?: string | null;
      title?: string | null;
    };
    Node: {
      _id: components["schemas"]["ObjectId"];
      color: string;
      createdAt: string;
      data: components["schemas"]["NodeData"];
      /** Format: double */
      height: number;
      updatedAt: string;
      /** Format: double */
      width: number;
      /** Format: double */
      x: number;
      /** Format: double */
      y: number;
    };
    /**
     * @description A node's data can either be a reference to a document or be a group container.
     *     Note: We need to add content to serde tag because serializing the struct as
     *     {"_type": "DocumentId", ...somehow inline ObjectId...} doesn't work with BSON
     */
    NodeData:
      | {
          _content: components["schemas"]["ObjectId"];
          /** @enum {string} */
          _type: "DocumentId";
        }
      | {
          _content: components["schemas"]["Group"];
          /** @enum {string} */
          _type: "Group";
        };
    NodeDataView:
      | (components["schemas"]["DocumentView"] & {
          /** @enum {string} */
          _type: "Document";
        })
      | (components["schemas"]["Group"] & {
          /** @enum {string} */
          _type: "Group";
        });
    /** @description This view modifies the node content to contain the S3 download URL if the content is of type File. */
    NodeEditorView: {
      _id: components["schemas"]["ObjectId"];
      color: string;
      createdAt: string;
      data: components["schemas"]["NodeDataView"];
      /** Format: double */
      height: number;
      updatedAt: string;
      /** Format: double */
      width: number;
      /** Format: double */
      x: number;
      /** Format: double */
      y: number;
    };
    /** @description Represents a MongoDB ObjectId in a format compatible with JSON Schema. */
    ObjectId: {
      $oid: string;
    };
    Operation:
      | (components["schemas"]["SetNameParams"] & {
          /** @enum {string} */
          _type: "setName";
        })
      | (components["schemas"]["CreateNodeParams"] & {
          /** @enum {string} */
          _type: "createNode";
        })
      | (components["schemas"]["SetNodePositionParams"] & {
          /** @enum {string} */
          _type: "setNodePosition";
        })
      | (components["schemas"]["SetNodeSizeParams"] & {
          /** @enum {string} */
          _type: "setNodeSize";
        })
      | (components["schemas"]["SetNodeTitleParams"] & {
          /** @enum {string} */
          _type: "setNodeTitle";
        })
      | (components["schemas"]["SetNodeFavoriteStateParams"] & {
          /** @enum {string} */
          _type: "setNodeFavoriteState";
        })
      | (components["schemas"]["SetNodeColorParams"] & {
          /** @enum {string} */
          _type: "setNodeColor";
        })
      | (components["schemas"]["SetNodeContentParams"] & {
          /** @enum {string} */
          _type: "setNodeContent";
        })
      | (components["schemas"]["AppendNodeContentParams"] & {
          /** @enum {string} */
          _type: "appendNodeContent";
        })
      | (components["schemas"]["DeleteNodeParams"] & {
          /** @enum {string} */
          _type: "deleteNode";
        })
      | (components["schemas"]["CreateEdgeParams"] & {
          /** @enum {string} */
          _type: "createEdge";
        })
      | (components["schemas"]["SetEdgeLabelParams"] & {
          /** @enum {string} */
          _type: "setEdgeLabel";
        })
      | (components["schemas"]["DeleteEdgeParams"] & {
          /** @enum {string} */
          _type: "deleteEdge";
        })
      | (components["schemas"]["SetEdgePositionParams"] & {
          /** @enum {string} */
          _type: "setEdgePosition";
        });
    S3Object: {
      bucket: string;
      file_type: string;
      key: string;
    };
    S3ObjectView: {
      download_url: string;
      file_type: string;
      key: string;
    };
    SetEdgeLabelParams: {
      id: string;
      label: string;
    };
    SetEdgePositionParams: {
      fromNodeId: string;
      fromSide: components["schemas"]["ConnectionSide"];
      id: string;
      toNodeId: string;
      toSide: components["schemas"]["ConnectionSide"];
    };
    SetNameParams: {
      name: string;
    };
    SetNodeColorParams: {
      color?: string | null;
      id: string;
    };
    SetNodeContentParams: {
      content: components["schemas"]["DocumentContentView"];
      id: string;
    };
    SetNodeFavoriteStateParams: {
      id: string;
      isFavorite: boolean;
    };
    SetNodePositionParams: {
      id: string;
      /** Format: double */
      x: number;
      /** Format: double */
      y: number;
    };
    SetNodeSizeParams: {
      /** Format: double */
      height: number;
      id: string;
      /** Format: double */
      width: number;
    };
    SetNodeTitleParams: {
      id: string;
      title?: string | null;
    };
    Website: {
      url: string;
    };
    Youtube: {
      videoId: string;
    };
    "api.create_canvas.Request": {
      description?: string | null;
      name?: string | null;
    };
    "api.create_canvas.Response": {
      canvas_id: components["schemas"]["ObjectId"];
    };
    "api.get_canvases.Response": {
      data: components["schemas"]["CanvasSummaryView"][];
    };
    "api.patch_canvas.Request": {
      operations: components["schemas"]["Operation"][];
    };
    "api.update_canvas.Request": {
      description?: string | null;
      edges?: components["schemas"]["Edge"][] | null;
      name?: string | null;
      nodes?: components["schemas"]["NodeEditorView"][] | null;
      pinned?: boolean | null;
      thumbnail_s3_key?: string | null;
    };
    "api.update_canvas.Response": {
      updated: boolean;
    };
    /** NOTE: Manually added — regenerate from backend OpenAPI spec once API key auth is enabled. */
    "api.get_upload_url.Request": {
      s3_key: string;
    };
    /** NOTE: Manually added — regenerate from backend OpenAPI spec once API key auth is enabled. */
    "api.get_upload_url.Response": {
      url: string;
      fields: Record<string, string>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  get_canvases: {
    parameters: {
      query?: {
        /** @description Filter canvases by pinned status */
        pinned?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Canvas retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["api.get_canvases.Response"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  create_canvas: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["api.create_canvas.Request"];
      };
    };
    responses: {
      /** @description Canvas created successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["api.create_canvas.Response"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_canvas_by_id: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The ID of the canvas to retrieve */
        canvas_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Canvas retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CanvasEditorView"];
        };
      };
      /** @description Invalid canvas ID supplied */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/plain": string;
        };
      };
      /** @description Canvas not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/plain": string;
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/plain": string;
        };
      };
    };
  };
  update_canvas: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The ID of the canvas to update */
        canvas_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["api.update_canvas.Request"];
      };
    };
    responses: {
      /** @description Canvas updated successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["api.update_canvas.Response"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  patch_canvas: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The ID of the canvas to update */
        canvas_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["api.patch_canvas.Request"];
      };
    };
    responses: {
      /** @description Canvas updated successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  /** NOTE: Manually added — regenerate from backend OpenAPI spec once API key auth is enabled. */
  get_upload_url: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["api.get_upload_url.Request"];
      };
    };
    responses: {
      /** @description Presigned upload URL generated successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["api.get_upload_url.Response"];
        };
      };
      /** @description Unauthorized — API key auth not yet available for this route */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
